package com.young.metro.theme
import androidx.compose.ui.graphics.Color

val metroLightPrimary = Color(0xFF006972)
val metroLightOnPrimary = Color(0xFFFFFFFF)
val metroLightPrimaryContainer = Color(0xFF8AF2FF)
val metroLightOnPrimaryContainer = Color(0xFF001F23)
val metroLightSecondary = Color(0xFF3B5BA9)
val metroLightOnSecondary = Color(0xFFFFFFFF)
val metroLightSecondaryContainer = Color(0xFFDAE2FF)
val metroLightOnSecondaryContainer = Color(0xFF001848)
val metroLightTertiary = Color(0xFF9B4052)
val metroLightOnTertiary = Color(0xFFFFFFFF)
val metroLightTertiaryContainer = Color(0xFFFFD9DD)
val metroLightOnTertiaryContainer = Color(0xFF400013)
val metroLightError = Color(0xFFBA1A1A)
val metroLightErrorContainer = Color(0xFFFFDAD6)
val metroLightOnError = Color(0xFFFFFFFF)
val metroLightOnErrorContainer = Color(0xFF410002)
val metroLightBackground = Color(0xFFFAFDFD)
val metroLightOnBackground = Color(0xFF191C1D)
val metroLightSurface = Color(0xFFFAFDFD)
val metroLightOnSurface = Color(0xFF191C1D)
val metroLightSurfaceVariant = Color(0xFFDAE4E5)
val metroLightOnSurfaceVariant = Color(0xFF3F484A)
val metroLightOutline = Color(0xFF6F797A)
val metroLightInverseOnSurface = Color(0xFFEFF1F1)
val metroLightInverseSurface = Color(0xFF2D3131)
val metroLightInversePrimary = Color(0xFF4ED8E7)
val metroLightShadow = Color(0xFF000000)
val metroLightSurfaceTint = Color(0xFF006972)

val metroDarkPrimary = Color(0xFF4ED8E7)
val metroDarkOnPrimary = Color(0xFF00363B)
val metroDarkPrimaryContainer = Color(0xFF004F56)
val metroDarkOnPrimaryContainer = Color(0xFF8AF2FF)
val metroDarkSecondary = Color(0xFFB2C5FF)
val metroDarkOnSecondary = Color(0xFF002B74)
val metroDarkSecondaryContainer = Color(0xFF1F428F)
val metroDarkOnSecondaryContainer = Color(0xFFDAE2FF)
val metroDarkTertiary = Color(0xFFFFB2BC)
val metroDarkOnTertiary = Color(0xFF5F1126)
val metroDarkTertiaryContainer = Color(0xFF7D293B)
val metroDarkOnTertiaryContainer = Color(0xFFFFD9DD)
val metroDarkError = Color(0xFFFFB4AB)
val metroDarkErrorContainer = Color(0xFF93000A)
val metroDarkOnError = Color(0xFF690005)
val metroDarkOnErrorContainer = Color(0xFFFFDAD6)
val metroDarkBackground = Color(0xFF191C1D)
val metroDarkOnBackground = Color(0xFFE0E3E3)
val metroDarkSurface = Color(0xFF191C1D)
val metroDarkOnSurface = Color(0xFFE0E3E3)
val metroDarkSurfaceVariant = Color(0xFF3F484A)
val metroDarkOnSurfaceVariant = Color(0xFFBEC8C9)
val metroDarkOutline = Color(0xFF899294)
val metroDarkInverseOnSurface = Color(0xFF191C1D)
val metroDarkInverseSurface = Color(0xFFE0E3E3)
val metroDarkInversePrimary = Color(0xFF006972)
val metroDarkShadow = Color(0xFF000000)
val metroDarkSurfaceTint = Color(0xFF4ED8E7)


val seed = Color(0xFF00AEBC)
